version: '3'
services:
  sentiment-analysis:
    build:
      context: .
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8050 --reload

  
  